### PR TITLE
install.sh separated into functions

### PR DESCRIPTION
**Pull request by luisejrobles**
as you said that the Issue was fixed by another person I consider this issue the one that introduced meinto 'bash scripting' so I'm going to submit my PR but if you want me to create docs or something I'll be happy to help!

### CODE REVIEW

**Comment by johncoleman83** [comment]
Hi @luisejrobles:

I like _**some**_ of what you've done.  If you can keep just the changes that I think are best, I will merge your changes, but it is a bit too much work for me to merge and then clean up after you.

* Please do not change the first 3 functions: `test_for_root_permissions()`, `establish_current_directory()`, and `assign_installation_variables`.
* Please do not remove the comments from @JiveCatDaddyO, they are helpful.
* keep this function you made: `installation_output()` that is very nice
* keep the fact that you removed whitespace.
* you don't have to rename this one: `install_directory_safety_checks()`.  The name you chose is actually misleading, because it is not JUST safety checks.
* you don't have to rename `install_files()` to `set_installation_directory()`, but I like that you created a new function `installed_files_permissions()`.  So you can keep that, but make the name of the installation function more clear.
* Please resolve the merge conflicts (that is actually not necessary, but it makes it a bit easier on me)
  * all you have to do is run a `$ git rebase upstream/master` and resolve the conflicts on your machin (Note upstream would refer to this repository, not yours)
  * or just start over and incorporate the requested changes, that is easy enough.

**Comment by johncoleman83** [comment]
Also, @luisejrobles, I forgot....  Thank you sincerely for your contribution.  If you can make these updates, be sure to add your name to the contributors list in the README.md and have fun taking notes!

**Comment by luisejrobles** [comment]
I'll do them this weekend 😄

**Comment by johncoleman83** [comment]
Awesome, I almost thought this was a lost cause

**Comment by luisejrobles** [comment]
sorry for the delay but I've been a little busy 🤐

**Comment by luisejrobles** [comment]
the changes are already in there!
if there's anything else just let me know

**Comment by johncoleman83** [comment]
LGTM, thanks @luisejrobles - Sorry it took me so long to review!

**Comment by luisejrobles** [comment]
no problem John I know you´re busy, have a great week!

**Pull request merged**
